name: Year

on:
  push:
    paths:
      - .github/workflows/year.yml
    branches:
      - main

jobs:
  execute:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run: echo 2022{01..12}
      - run: php year.php
        env:
          SHELL: /bin/bash
